### ISSUE TITLE
 There was no endpoint listening at https://w1.mercurydev.net/ws/ws.asmx that could accept the message.

### ISSUE THREAD

**Issue by manelandrea** [MercuryPay/Gift_WebServices.CSharp#1]
I tried running the solution but it throws the error:

 There was no endpoint listening at https://w1.mercurydev.net/ws/ws.asmx that could accept the message. This is often caused by an incorrect address or SOAP action. 
![image](https://user-images.githubusercontent.com/8605117/35723930-3eac09c0-07b9-11e8-8ddd-a234cebb5768.png)

**Comment by dourada** [comment]
Apologies for the slow response.  Please try:  https://w1.mercurycert.net/ws/ws.asmx
